site_name: Slurm Workflow Utils
# dev_addr: 127.0.0.1:8081
theme:
  name: material
  # features:
  #   - navigation.tabs
  #   - navigation.sections
  #   - toc.integrate
  #   - navigation.top
  #   - search.suggest
  #   - search.highlight
  #   - content.tabs.link
  #   - content.code.annotation
  #   - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      # python:
      handlers:
        python:
          paths: [slurm_workflow_utils]
        # import_root: jira_python_utils
        # import_root: jira-python-utils
nav:
  - Home: index.md
  - Installation: INSTALL.md
  - Code Reference:
  # INSERT CODE REFERENCE SECTION
    - Builder: builder.md
    - Console Helper: console_helper.md
    - Constants: constants.md
    - File Utils: file_utils.md
    - Launcher: launcher.md
    - System Caller: system_caller.md
    - Workflow Builder: workflow_builder.md
    - Workflow Launcher: workflow_launcher.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/jai-python3"  target="_blank" rel="noopener">Jai Python3</a>
